<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManageUsers.aspx.cs" Inherits="WebApplication1.ManageUsers" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link rel="stylesheet" href="/css/Grid_view.css" />
    <link rel="stylesheet" href="/css/AdminDashboard.css" />

</head>
<body>
    <form id="form1" runat="server">
        <div class="sidebar">
            <h2 class="logo">REMS</h2>

            <a href="AdminDashboard.aspx">Dashboard</a>
            <a href="ManageProperties.aspx">Properties</a>
            <a href="ManageUsers.aspx">Users</a>
            <a href="ManageBookings.aspx">Bookings</a>
            <a href="../Logout.aspx">Logout</a>
        </div>
        <div class="main-content">
            <h1 class="page-title">Manage Users</h1>
            <div class="grid-wrapper">
            <asp:GridView ID="gv_user" runat="server"
                CssClass="gv-style"
                AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="UserId" OnRowCancelingEdit="gv_user_RowCancelingEdit" OnRowDeleting="gv_user_RowDeleting" OnRowEditing="gv_user_RowEditing" OnRowUpdating="gv_user_RowUpdating">
            </asp:GridView>
                </div>
        </div>
    </form>
</body>
</html>
