<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ViewList.aspx.cs" Inherits="WebApplication1.Admin.Dashboard" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
   <link rel="stylesheet" href="/css/AdminDashboard.css?v=2" />
<link rel="stylesheet" href="/css/Grid_view.css?v=2" />

</head>
<body>
    <body>
    <form id="form1" runat="server">

        <!-- Sidebar -->
        <div class="sidebar">
            <h2 class="logo">REMS</h2>

            <a href="AdminDashboard.aspx">Dashboard</a>
            <a href="ManageProperties.aspx">Properties</a>
            <a href="ManageUsers.aspx">Users</a>
            <a href="ManageBookings.aspx">Bookings</a>
            <a href="Logout.aspx">Logout</a>
        </div>

        <!-- Main Content -->
        <div class="main-content">
            <h2 class="page-title">View Details</h2>

            <!-- Toolbar -->
            <div class="toolbar">
                <asp:TextBox ID="txtSearch" runat="server"
                    CssClass="search-input"
                    Placeholder="Search..." />

                <asp:Button ID="btnSearch" runat="server"
                    CssClass="btn btn-search"
                    Text="Search"
                    OnClick="btnSearch_Click" />

                <asp:Button ID="btnAdd" runat="server"
                    CssClass="btn btn-add"
                    Text="Add New"
                    OnClick="btnAdd_Click" />
            </div>

            <!-- Grid -->
            <div class="grid-wrapper">
                <asp:GridView ID="gv_viewList" runat="server"
                    CssClass="gv-style"
                    AutoGenerateColumns="true"
                    AutoGenerateEditButton="true"
                    AutoGenerateDeleteButton="true"
                    OnRowEditing="gv_viewList_RowEditing"
                    OnRowUpdating="gv_viewList_RowUpdating"
                    OnRowCancelingEdit="gv_viewList_RowCancelingEdit"
                    OnRowDeleting="gv_viewList_RowDeleting">
                </asp:GridView>
            </div>
        </div>

    </form>
</body>

</body>
</html>
